http.host: 0.0.0.0
xpack.monitoring.elasticsearch.hosts:
- http://172.20.0.2:9200
xpack.monitoring.elasticsearch.password: SOC_Lab_2025!Secure
xpack.monitoring.elasticsearch.username: elastic
xpack.monitoring.enabled: false
